# Generated by Django 3.2.7 on 2024-02-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_desc', models.CharField(max_length=150)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status', models.CharField(max_length=150)),
                ('item_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.customer_reg')),
            ],
        ),
    ]
