# Generated by Django 3.2.7 on 2024-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_master_id', models.CharField(max_length=150)),
                ('item_id', models.CharField(max_length=150)),
                ('cart_qty', models.PositiveIntegerField()),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='cart_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customert_id', models.CharField(max_length=150)),
                ('cart_tot_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_status', models.CharField(max_length=150)),
            ],
        ),
    ]
