# Generated by Django 3.2.7 on 2024-02-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_tbl_cassign_tbl_courier_tbl_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_status', models.CharField(max_length=150)),
                ('item_image', models.FileField(max_length=150, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.subcategory')),
            ],
        ),
    ]
