# Generated by Django 3.2.7 on 2024-02-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_tbl_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_item',
            name='item_desc',
            field=models.CharField(max_length=500),
        ),
    ]
