# Generated by Django 3.2.7 on 2024-02-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_tbl_item_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_item',
            name='recipe_status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_desc', models.CharField(max_length=500)),
                ('recipe_name', models.CharField(max_length=150)),
                ('pre_time', models.CharField(max_length=150)),
                ('cook_time', models.CharField(max_length=150)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tbl_item')),
            ],
        ),
    ]
