# Generated by Django 3.2.7 on 2024-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20240223_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_recipes',
            name='recipe_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
