# Generated by Django 3.2.7 on 2024-02-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_tbl_recipes_recipe_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ingrediantcalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediant', models.CharField(max_length=150)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tbl_item')),
            ],
        ),
    ]
