# Generated by Django 3.2.7 on 2024-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_tbl_ingrediantcalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_reg',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
