# Generated by Django 3.2.7 on 2024-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_staff_reg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payment',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
